### ISSUE TITLE
Errors while deploying

### ISSUE THREAD

**Issue by Ayushdeveloper001** [Dovakiin0/Kitsune#54]
![IMG_20231204_193809](https://github.com/Dovakiin0/Kitsune/assets/117559953/9c122ac3-1c5a-414f-91d8-0b697ffde20f)
![IMG_20231204_193752](https://github.com/Dovakiin0/Kitsune/assets/117559953/98f7735e-c9de-4724-a2cc-e80e5180ccc6)

Please check this what's up with this

**Comment by Dovakiin0** [comment]
These are just warning and not actual errors
As for deployment, you just need TMDB Api read access token and everything else is good to go
