### ISSUE TITLE
Not working on Vercel

### ISSUE THREAD

**Issue by dillfrescott** [Dovakiin0/Kitsune#59]
Hello. I am deploying this on Vercel and put in my tmdb write access token as the env variable and deployed and all its saying is "something went wrong"

the browser console isnt helpful.

**Comment by Dovakiin0** [comment]
i noticed there was some problem with deploying on vercel
i havent got time to replicate the issue yet

first make sure the tmdb key is `API Read Access Token` 
second you will need to make some minor changes
such as changing `DOMAIN_URL` to `VERCEL_URL`  in env and 
https://github.com/Dovakiin0/Kitsune/blob/fd006b7f420efbae9aea1b1630dea96e9a2a6c60/src/utils/constants.ts#L2 
here

VERCEL_URL will be injected automatically by vercel

**Comment by dillfrescott** [comment]
Okay! Thanks for the info, I'll try it in a bit.

**Comment by dillfrescott** [comment]
Ok I tried it and its still doing the same thing :(

**Comment by dillfrescott** [comment]
```
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
```

**Comment by Vibhav1207** [comment]
Do you still want help deploying the site on vercel?

**Comment by dillfrescott** [comment]
No thank you. But I appreciate the offer! I'll close this I suppose...
